/*
 * CH32H417QEU6 (QingKe V3F / boot core) linker memory map.
 *
 * This overrides the `memory.x` generated by `ch32-metapac/memory-x`.
 * That generated script names the RAM regions ITCM/DTCM/SRAM_SHARED but
 * never declares a region literally called `RAM`, while `qingke-rt`'s
 * `link.x` places `.data`/`.bss`/`.uninit` and the stack in `>RAM`
 * (and derives `_stack_start` from `REGION_STACK`). Without a `RAM`
 * region the link fails with "memory region 'RAM' not declared".
 *
 * Keep the full metapac region list so nothing that relies on the other
 * H417 regions changes, and alias `RAM` to ITCM — the same primary RAM
 * region metapac itself picks for REGION_DATA/REGION_BSS/… on this chip.
 */
MEMORY
{
    CODE   (rx)  : ORIGIN = 0x00000000, LENGTH =  960K /* USR boot alias */
    USR    (rwx) : ORIGIN = 0x08000000, LENGTH =  960K
    SYS    (rwx) : ORIGIN = 0x1FFF0000, LENGTH =   56K
    VND    (r)   : ORIGIN = 0x1FFFF700, LENGTH =   256
    OPT    (rw)  : ORIGIN = 0x1FFFF800, LENGTH =   256
    ITCM   (rwx) : ORIGIN = 0x200A0000, LENGTH =  128K
    DTCM   (rwx) : ORIGIN = 0x200C0000, LENGTH =  256K
    SRAM_SHARED (rwx) : ORIGIN = 0x20100000, LENGTH =  512K
}

REGION_ALIAS("FLASH", CODE);
/* Required by qingke-rt's link.x. */
REGION_ALIAS("RAM", ITCM);

REGION_ALIAS("REGION_TEXT", CODE);
REGION_ALIAS("REGION_RODATA", CODE);
REGION_ALIAS("REGION_DATA", ITCM);
REGION_ALIAS("REGION_BSS", ITCM);
REGION_ALIAS("REGION_HEAP", ITCM);
REGION_ALIAS("REGION_STACK", ITCM);
