fn main() {
    // Link order matters: link.x INCLUDEs memory.x, so the shared-region
    // fragment (which names SRAM_SHARED) has to come after it.
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tshared.x");

    // Ship this crate's linker scripts. qingke-rt's link.x wants `memory.x` (our
    // V5F FLASH/RAM/DTCM layout, overriding the one metapac generates) and
    // `device.x` (the svd2rust device-crate hook, which a HAL-free crate provides
    // empty); `shared.x` *reserves* SRAM_SHARED so nothing of ours lands there —
    // the mailbox itself is defined by the boot core, not by this image.
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_dir = std::path::PathBuf::from(out_dir);
    std::fs::write(out_dir.join("memory.x"), include_bytes!("memory.x")).unwrap();
    std::fs::write(out_dir.join("device.x"), include_bytes!("device.x")).unwrap();
    std::fs::write(out_dir.join("shared.x"), include_bytes!("../ipc/shared.x")).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=device.x");
    println!("cargo:rerun-if-changed=../ipc/shared.x");

    // The layout the boot core (V3F) defined, post-processed by `xtask` from the
    // V3F ELF into `../out/layout.txt`. `xtask` points us at it through
    // H417_LAYOUT; a standalone build picks up the same file by convention.
    let layout = match std::env::var("H417_LAYOUT") {
        Ok(path) => std::path::PathBuf::from(path),
        Err(_) => std::path::PathBuf::from("../out/layout.txt"),
    };
    let text = std::fs::read_to_string(&layout).unwrap_or_else(|e| {
        panic!(
            "cannot read the V3F layout at {}: {e}\n\
             build the boot core first, e.g. `cargo xtask build --example dualcore --dual-core`\n\
             (all shared symbols are defined by the V3F image; the V5F only consumes their address)",
            layout.display()
        )
    });

    let value = |key: &str| -> u32 {
        let line = text
            .lines()
            .find(|line| line.starts_with(key))
            .unwrap_or_else(|| panic!("{key} missing from {}", layout.display()));
        let raw = line.split_whitespace().nth(1).expect("key value");
        u32::from_str_radix(raw.trim_start_matches("0x"), 16).expect("hex value")
    };

    let generated = format!(
        "// generated by v5f/build.rs from {} — do not edit\n\
         pub const MAILBOX_ADDR: usize = {:#010x};\n\
         pub const MAILBOX_SIZE: usize = {:#x};\n\
         pub const LAYOUT_VERSION: u32 = {};\n",
        layout.display(),
        value("mailbox_addr"),
        value("mailbox_size"),
        value("layout_version"),
    );
    std::fs::write(out_dir.join("layout.rs"), generated).unwrap();
    println!("cargo:rerun-if-changed={}", layout.display());
}
