[package]
name = "ch32h417-v5f"
version = "0.1.0"
edition = "2021"

[dependencies]
ch32-hal = { path = "../../", features = [
    "ch32h417qeu6-v5f",
    "memory-x",
] }
qingke = { version = "0.7" }
qingke-rt = "0.7"
panic-halt = "1.0"

[profile.release]
debug = 2
strip = false
lto = false
opt-level = 3

[patch.crates-io]
qingke = { path = "/Users/mono/Elec/WCH/qingke" }
qingke-rt = { path = "/Users/mono/Elec/WCH/qingke/qingke-rt" }
