MEMORY
{
    FLASH : ORIGIN = 0x08002000, LENGTH = 960K - 8K
    RAM : ORIGIN = 0x200C0000, LENGTH = 256K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_STACK", RAM);
