fn main() {
    println!("cargo:rustc-link-arg-bins=-Tlink.x");

    // Ship a H417-specific memory.x, overriding the one generated by
    // `ch32-metapac/memory-x` (which has no `RAM` region required by
    // qingke-rt's link.x). The current crate's build-script link search
    // path takes precedence over dependency build-script paths.
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_dir = std::path::PathBuf::from(out_dir);
    std::fs::write(out_dir.join("memory.x"), include_bytes!("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=memory.x");
}
