/*
 * CH32H417QEU6 (QingKe V3F / boot core) linker memory map.
 *
 * Flash/RAM partition mirrors the WCH CSDK's dual-core layout
 * (`CH32H417EVT/EXAM/.../Common/Ld/V3F/Link_v3f.ld` + `Ld/V5F/Link_v5f.ld`):
 *
 *   V3F : flash 0x00000000 + 64K,  RAM = ITCM
 *   V5F : flash 0x00010000 + ...,  RAM = DTCM (head reserved for the
 *         hardware push/pop area)
 *   both: RAM_SHARED 0x20178000 + 32K — cross-core mailbox, the same
 *         address in both linker maps
 *
 * Each image states its own range, so a V3F image growing past 64K is a
 * link error rather than silently overwriting the V5F image (the CSDK
 * reserves the first 64K for V3F for exactly this reason).
 *
 * This also overrides the `memory.x` generated by `ch32-metapac/memory-x`:
 * that script names the H417 RAM regions ITCM/DTCM/SRAM_SHARED but never
 * declares a region literally called `RAM`, while `qingke-rt`'s `link.x`
 * places `.data`/`.bss`/`.uninit` and the stack in `>RAM`.
 */
MEMORY
{
    CODE   (rx)  : ORIGIN = 0x00000000, LENGTH =  64K  /* USR boot alias; V3F flash slot */
    USR    (rwx) : ORIGIN = 0x08000000, LENGTH =  64K  /* the same window through 0x08000000 */
    SYS    (rwx) : ORIGIN = 0x1FFF0000, LENGTH =   56K
    VND    (r)   : ORIGIN = 0x1FFFF700, LENGTH =   256
    OPT    (rw)  : ORIGIN = 0x1FFFF800, LENGTH =   256
    ITCM   (rwx) : ORIGIN = 0x200A0000, LENGTH =  128K /* V3F code/data; DTCM belongs to the V5F */
    SRAM_SHARED (rwx) : ORIGIN = 0x20178000, LENGTH = 32K /* cross-core mailbox */
}

REGION_ALIAS("FLASH", CODE);
/* Required by qingke-rt's link.x. */
REGION_ALIAS("RAM", ITCM);

REGION_ALIAS("REGION_TEXT", CODE);
REGION_ALIAS("REGION_RODATA", CODE);
REGION_ALIAS("REGION_DATA", ITCM);
REGION_ALIAS("REGION_BSS", ITCM);
REGION_ALIAS("REGION_HEAP", ITCM);
REGION_ALIAS("REGION_STACK", ITCM);
