[build]
target = "riscv32ec-unknown-none-elf.json"

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
# runner = "riscv64-unknown-elf-gdb -q -x openocd.gdb"
# runner = "riscv-none-embed-gdb -q -x openocd.gdb"
# runner = "gdb -q -x openocd.gdb"
# runner = "wlink -v flash"

runner = "wlink -v flash --enable-sdi-print --watch-serial"

# Flash and debug chip with probe-rs. https://probe.rs/
# runner = "probe-rs run --chip ch32v003"

[unstable]
build-std = ["core"]
# build-std = ["core", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]

[target."riscv32ec-unknown-none-elf"]
rustflags = [
#  "-C", "link-arg=-Tlink.x",
]
