[build]
target = "riscv32imafc-unknown-none-elf.json"

[unstable]
build-std = ["core"]
json-target-spec = true

[target.riscv32imafc-unknown-none-elf]
runner = "wlink flash --enable-sdi-print --watch-serial"
